# Generated by Django 4.0.2 on 2022-03-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_issue_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="app.issue",
            ),
        ),
    ]
