# Generated by Django 4.0.2 on 2022-07-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="app.project",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                max_length=8,
            ),
        ),
    ]
